### ISSUE TITLE
How to know which panel is has loaded/unloaded when using data-load/data-unload

### ISSUE THREAD

**Issue by jahflasher** [01org/appframework#199]
I am new  at any serious JavaScript and want to call a function every time a panel is loaded/unloaded. Since all the panels call the same JavaScript without passing parameters how can identify each panel? Typically all panels will look like this with the only difference going to be the id,title and defer:

```
       <div class="panel" id="search" data-load="loadmoretidy" data-unload="unloadmoretidy" data-defer="html_fragments/search.html" title="Search"></div>
```

Thanks in advance.

**Comment by jokabuyasina** [comment]
hello imaffett 
i wanted to know is it possible to pass a function with parameters in data-load ???
