### ISSUE TITLE
Can't hide side menu on Android tablet

### ISSUE THREAD

**Issue by jmumby** [01org/appframework#230]
Using an Android tablet the $.ui.disableSideMenu(); does not work but is fine on a Android handset. I want to use a side nav menu but only after a user has logged in.

**Comment by franciscocorrales** [comment]
It is not working for me. Is this to hide the 

`<div id="menu" class="tabletMenu" `

?

**Comment by imaffett** [comment]
@franciscocorrales  - please provide a sample for us to debug
