### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined at file:///android_asset/www/index.html:2

### ISSUE THREAD

**Issue by abhishekbedi** [01org/appframework#292]
I apologize in advance if being silly ! There could be a very simple answer to this issue, fairly new to appframework,  badly need help !!

**_Using Phonegap/Cordova 2.5.0, App Framework 1.2 , have also tested with App Framework 2.0.**_

A simple ajax request not working with the server (GoDaddy). Perfectly working on localhost using Ripple Emulator for PhoneGap.

Have tested the app using Ripple Emulator : Works with the server, only when 'CrossDomain Proxy' is disabled. When the **_'CrossDomain Proxy'**_  is enabled I get the following error:

_Uncaught ReferenceError: jQuery is not defined (anonymous function) 
$.parseJS appframework.js:2642 
$.ajax.xhr.onreadystatechange  
GET : localhost:8080/_dm/s/rt/scripts/duda-js-runtime-package.min.js? version=2013-06-23T09:35:31 404 (Not Found)._

Also, when I run the application on an **_Android Phone (2.3.6)**_ I get the following error :

**_Uncaught ReferenceError: jQuery is not defined at file:///android_asset/www/index.html:2**_

I have already added localhost,my domain and \* to the whitelist in config.xml (PhoneGap).

``` xml
 <access origin="http://127.0.0.1*"/> <!-- allow local pages -->
 <access origin="http://www.mydomain.com*" subdomains="true" /> 
 <access origin="*" subdomains="true" /> 
 <access origin="http://*" subdomains="true" /> 
```

Also added CrossDomain enabling on the server side, using php code:

``` php
header('Access-Control-Allow-Origin:'*');
```

Still the Ajax request doesn't work. I send the request, using simple code :

``` javascript
$.ajax({
    url: "http://mydomain.com//test.php",
    data: str, // passed in to the function
    type: "POST",
    timeout:10000,
    dataType: "html",
    success: function(response) {
    $.ui.hideMask();
//  alert("Success: " + response);     
     redirection(response);      
    },
    error: function(request, status, error) {
    //$.mobile.loading( 'hide');
    $.ui.hideMask();
    alert('Please try again');
      console.log("Error status " + status);
      console.log("Error request status text: " + request.statusText);
      console.log("Error request status: " + request.status);
      console.log("Error request response text: " + request.responseText);
      console.log("Error response header: " + request.getAllResponseHeaders());
      $("#error").html(status);
    } 

    });
```

I have also tried with :

``` javascript
$.get("http://mydomain.com/test.php?user=dsnlsflsaf00&pass=bar?foo=bar",function(res){console.log(res)});
```

still doesn't work and keep getting jQuery not defined error.

**_Just tested the app on Android 4.0.4 and it works fine.**_

Any help in this regards is really appreciated.

Cheers

**Comment by blacksunset** [comment]
+1 in android 7 , looks like cache problem
