### ISSUE TITLE
Android Phonegap Scroll is Very Choppy

### ISSUE THREAD

**Issue by ghost** [01org/appframework#587]
I'm building a webapp that displays list items as the following--very large by using App Framework!

<p>
    &lt;ul id="J_stuffs" class="cfx"&gt;
</p>

<p>
    <span style="line-height:1.5;">&nbsp;&nbsp;&nbsp;&nbsp;&lt;li class="stuff_rcd"&gt;</span>
</p>

<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="pic"&gt;&lt;img src="xxxxxxx_s.jpg"&gt;&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="info"&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="top"&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span class="title ofh"&gt;百味来袋装蝴蝶意大利通心粉&lt;/span&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;span class="fr"&gt;&lt;i class="fa fa-heart"&gt;&lt;/i&gt; 500&lt;/span&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="alias ofh"&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;i class="label"&gt;别名:&lt;/i&gt;&lt;i class="val"&gt;意大利通心粉&lt;/i&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div class="intro"&gt;通心粉亦称通心面，在国外已是极普通的面制品之一，我国上海...&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;a href="#stuff_detail/55" class="goto"&gt;&lt;/a&gt;<br />
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/li&gt;
</p>

<p>
    &nbsp; &nbsp; &lt;!-- more lists here --&gt;
</p>

<p>
    &lt;/ul&gt;
</p>

I'm using phonegap to port it to a _native_ app on Android and I'm have a bit of trouble with the scrolling by using af.scroller.js plugin.

It works perfectly when the list is small.  However the scroll becomes very "choppy" and skips and sticks when loading more and more list items. 

I've tested  webapp on  devices from Samsung i9100 with Android 2.3 and Samsung i9300 with Android 4.1. 

Hopefully somebody can give me some advice! Thanks in advance!

**Comment by aartpieete** [comment]
Hi,

I am a novice, and not sure what code to put up, using app framework/phone gap. All works fine on iOS but on Android nothing will scroll. I realize this is a very unspecific question, but any support/help would be very welcome. tx!
