### ISSUE TITLE
How to assign custom footer using $.ui.addContentDiv();

### ISSUE THREAD

**Issue by willyguevara** [01org/appframework#679]
Hi, im loading content dinamically using <code>$.ui.addContentDiv();</code>
how can i specify the footer for the new div created dinamically.

Thanks.

**Comment by vijayrajasekaran** [comment]
Can someone give an example to add a footer dynamically?
Thanks.

**Comment by imaffett** [comment]
@vijayrajasekaran which version of App Framework?

**Comment by vijayrajasekaran** [comment]
2.2

**Comment by vijayrajasekaran** [comment]
This is code i used now,

    $.ui.addContentDiv("panel","<div id = 'paneldata'></div><div id='panel' data-footer='af-footer-1'></div><header><a class='button backButton'>Back</a><h1>panel</h1></header>");
    $.ui.loadContent("panel", false, false, "none");

**Comment by imaffett** [comment]
http://app-framework-software.intel.com/af22/api.php#$_ui_addContentDiv

Your HTML you are passing in is incorrect.  get rid of the first two divs.  It *creates and wires* the scrolling div for you

```
    $.ui.addContentDiv("panel","<header><a class='button backButton'>Back</a><h1>panel</h1></header>This is some content");
````

**Comment by vijayrajasekaran** [comment]
Thank you for the clear code but how do i add data-footer="af-footer-1" to the dynamically created panel.

**Comment by imaffett** [comment]
````
    $('#panel').attr("data-footer","af-footer-1");
```

**Comment by vijayrajasekaran** [comment]
Thank you so much, worked perfect.. :-)
