### ISSUE TITLE
Scrolling to a div.

### ISSUE THREAD

**Issue by mansilladev** [01org/appframework#751]
Using the following code only seems to work for divs that have a class of "panel".

```
$.ui.scrollingDivs['foo'].scrollToTop()
```

Is there any way around that? I'm constructed a div by hand in one of the widget containers nestled somewhere far down in the DOM. Without the "panel" class it just shows up, and is happy; however, the moment I add it, it seems I have to do quite a bit of explicit styling in order for it to be visible and stretch to the content.

p.s. Got the code above from #352.

**Comment by vinaybr** [comment]
any updates on this issue, i am facing the same problem. I have tried the code snippet mentioned on chrome desktop browser and on android phonegap app as well.

**Comment by imaffett** [comment]
Nope - no one has provided a sample that replicates the issue.
