### ISSUE TITLE
Is it a bug? jQuery conflict with jq.appframework.js plugin

### ISSUE THREAD

**Issue by Hammer2014** [01org/appframework#774]
<p>
please see the comment in script.
<pre>
<code>
$(function(){
            $('#switch').click(function(e) {
                // HTML:  id="aboutSwitch" class="collapsed"
                // When using jq.appframework.js & jquery-2.1.1.js 
                // the "$(this)" is not same to "$('#switch')" object!
                // if using jQuery or appframework alone, everything is ok.
                // is it a bug?
                // jquery-2.1.1.js conflict with jq.appframework.js ?
                $(this).toggleClass('collapsed');
            });
        })
</code>
</pre>
</p>

**Comment by marinusdewilde** [comment]
hi Luiscarlostic,

Maybe i am doing something wrong, but from my understanding above you are saying...lets take example, new project login view app, all i have to do is to remove 

        <script type="application/javascript" src="app_framework/2.1/appframework.js"></script>
        <script type="application/javascript" src="app_framework/2.1/appframework.ui.js" data-ver="1"></script>

and replace with ??

the moment i include script to jquery the app goes blank, should i not include jquery but rather use af.ui.jquery..?? 

how do i go about this?

**Comment by imaffett** [comment]
You include the following

1) jquery
2) af.ui.jquery.js

**Comment by imaffett** [comment]
Also - for questions about App Designer projects in the XDK, go to https://forums.html5dev-software.intel.com/

**Comment by luiscarlostic** [comment]
Hi, I fixed it by using only 2 scripts

<script src="jquery-1.11.1.min.js"></script>
<script src="af.ui.jquery.min.js"></script>

**Comment by marinusdewilde** [comment]
great stuff...it is working.......

i will post on forum suggested.
