### ISSUE TITLE
Pull to refresh doesn't work properly on iOS 8

### ISSUE THREAD

**Issue by linoleum89** [01org/appframework#808]
I'm facing an issue with pull to refresh on iOS, in iphone 5s device where sometimes the refresh-release event is not firing, instead, the refresh-cancel event is firing so don't let me to fetch my new content, also when it's possible to make the pull to the refresh, the screen doesn't show the "Release to refresh" word when you are pulling the screen, this not happen on iOS 7, you can pull but you aren't notice that you can release to refresh, do you have any workaround for this? thanks.

**Comment by imaffett** [comment]
Can you put a demo up?

**Comment by linoleum89** [comment]
You can download a sample here: https://mega.co.nz/#!7dIVRJbS!nPJMqA46iI-A5hALjAnplO_XhKcN7COdlCsM2pFrgzk

To pull to regresh I only use the code that you suggested on kitchen sink, but if you need more info please let me know

**Comment by linoleum89** [comment]
Sorry my mistake, adding $.feat.nativeTouchScroll=false; just worked, the weird thing is that works too without that in some scenarios, like in the video, but with that enabled the word "Release to refresh" now appears.
