### ISSUE TITLE
radio buttons is not displaying correctly on android

### ISSUE THREAD

**Issue by SlavaVolkov** [01org/appframework#809]
Hi, sorry for my English. I have a problem with displaying group of radio buttons on Android device - HUAWEI G730-U10, version of Android 4.2.2, you can see screenshot with incorrect displaying below:
![not_correct](https://cloud.githubusercontent.com/assets/10748073/5947780/7360cbb2-a748-11e4-9cd1-386a3abdec05.png)
But on other android and ios devices radio buttons displaying correctly, like this: 
![correct](https://cloud.githubusercontent.com/assets/10748073/5947781/78a283fe-a748-11e4-946b-8da61cbcf0f1.png)
Do you have any workaround for this? thank you very much!

**Comment by imaffett** [comment]
Sorry - I would need access to that device since I cannot replicate it.  Hopefully someone from the community can help you debug it!

**Comment by SlavaVolkov** [comment]
I've resolve the problem, webview of this device is not support css3 border-radius, that why radio buttons not display correctly.I draw custom radio buttons with images,
For more info on the cause of this bug, see:
http://stackoverflow.com/questions/17186158/galaxy-s4-stock-browser-css3-border-radius-support
