### ISSUE TITLE
Square Android Popup in version 3.0

### ISSUE THREAD

**Issue by leocrawf** [01org/appframework#810]
I have been using the https://github.com/01org/appframework/tree/3.0beta version of the framework. All works well except that when I test on an android device I get default square android themed popup , instead of the none os theme i see on the desktop. I went as far as comment out the android specific popup css in the af.ui.css file but I still see the os themed popup. is there a way to fix this? I know that this is a beta but all seem to work well except this.

in my code I have $.afui.useOSThemes=false; but this seem to not make a difference.

**Comment by imaffett** [comment]
Can you put a demo up and let me know the device?  I'll look into it ASAP

**Comment by leocrawf** [comment]
Here goes: http://deleovon.com/fix/ . If you test on chrome it works at it should. it you test in android browser is shows

**Comment by imaffett** [comment]
I just tested your page and I see the correct popup.  Which "Android browser" were you testing in?

**Comment by imaffett** [comment]
Your problem is you are setting $.afui.useOSThemes=false; in the $.afui.ready function.  That gets set AFTER $.afui has launched.  Move it before and it will work.

**Comment by leocrawf** [comment]
thanks. its now fixed.
