### ISSUE TITLE
jQuery Ajax Conflict

### ISSUE THREAD

**Issue by lincanbin** [01org/appframework#811]
There seems to be a Bug after [Using JQuery](http://app-framework-software.intel.com/documentation.php#afui/afui_jquery). 
I have reproduced this conflict in jQuery v1.11.2 with Intel appframework [af.popup.js](https://github.com/01org/appframework/blob/master/plugins/af.popup.js)
Demo: 
```javascript
	$("#afui").popup({
		title: 'test',
		message: "test",
		cancelText: "cancel",
		cancelCallback: function(){},
		doneText: "Done",
		doneCallback: function(){
			$.ajax({
				url: '/reply',
				data:{
					TopicID: 123
				},
				type: 'post',
				dataType: 'json',
			});
		},
		cancelOnly: false
	});
```
Clicked the "Done" Button: 
```
Uncaught TypeError: object is not a function jquery.js:4
m.extend.ajax jquery.js:4
Reply.$.popup.doneCallback global.js
(anonymous function) appframework.popup.js 126
m.event.dispatch jquery.js:3
r.handle jquery.js:3
```
![qq 20150131214919](https://cloud.githubusercontent.com/assets/5785188/5988253/096611ca-a993-11e4-84d5-ec17e02b6398.png)

**Comment by imaffett** [comment]
We support jQuery 2.x series

**Comment by lincanbin** [comment]
Still face the same conflict after I replaced it with jQuery 2.1.3.

**Comment by imaffett** [comment]
Are you using App Framework UI, or just the popup.  Can you put an example somewhere so I can test it?
