### ISSUE TITLE
ios document ready not fired

### ISSUE THREAD

**Issue by mouhammad-zd** [01org/appframework#813]
Hello i am using your new update and i have no luck to let document ready function to be fired

simply

$(document).ready(function(){alert('initialized');});

will not alert anything when old versions of framework working as needed but scroller fix is missed so iam obligated to use your latest version .

Any suggestion or idea ! Thank you in advance for any regards !

**Comment by imaffett** [comment]
Please post a full example somewhere, otherwise we can't help debug

**Comment by mouhammad-zd** [comment]
This is the logic of my code :

var app = 
        {
            config : {
                        web_id : 1,
                        os : 'android',
                        language : 'English',
                        version : 1,
                        admob_id : null,
                        analytics_id : '',
                        app_store : null,
                        api_link : null,
                        web_link : "",
                        //web_link : "",
                        upload_user_picture_path : null,
                        upload_video_path : null,
                        upload_image_path : null,
                        store :
                                {
                                      'android' : '',
                                      'ios' : ''
                                },
                        ad_units :
                          {
                              android : {
                                          banner: '',
                                          interstitial: ''
                                        },
                              ios     : {
                                          banner: '',
                                          interstitial: ''
                                        }
                          }
                     },
            is_ready : 0,
            debug_mode : 1,
            have_back : 0,
            operation : '',
            current_page : '',
            current_program : '',
            sender_id : '',
            initialize : function()
                {
                    this.config.admob_id = ( /(android)/i.test(navigator.userAgent) ) ? this.config.ad_units.android : this.config.ad_units.ios;
                    this.config.app_store = this.config.store[this.config.os];
                    this.config.api_link = this.config.web_link + "Programs/demo/demo.php";
                    this.config.upload_user_picture_path = this.config.web_link + "Programs/demo/upload_user_pic.php";
                    this.config.upload_video_path = this.config.web_link + "Programs/demo/upload_video.php";
                    this.config.upload_image_path = this.config.web_link + "Programs/demo/upload_image.php";
                    core.bind_system_events();
                }
        }
		
var core = 
        {
            bind_system_events : function()
                {
                    $(document).ready(this.validate_application_version);
                },
        };
		
app.initialize();

In this scenario document ready is not loaded when using your latest update of framework

Any help !

**Comment by imaffett** [comment]
Again, you need to have everything up so I can test.  You could be missing a file, have includes in the wrong order, etc.

**Comment by mouhammad-zd** [comment]
<code>
<!DOCTYPE html>
<html>
    <head>
        <title>World Deaf</title>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" type="text/css" href="appframework/build/css/icons.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/forms.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/buttons.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/afui.css" />
        <link rel="stylesheet" type="text/css" href="appframework/plugins/css/af.popup.css" />
        <link rel="stylesheet" type="text/css" href="styles/style-ltr.css?v=2" />
        <script type="text/javascript" charset="utf-8" src="appframework/build/ui/appframework.ui.min.js"></script>
        <link rel="stylesheet" type="text/css" href="appframework/plugins/css/af.selectBox.css" />
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.selectBox.js"></script>
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.passwordBox.js"></script>
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.popup.js"></script>
        <script>
            if (!((window.DocumentTouch && document instanceof DocumentTouch) || 'ontouchstart' in window))
                {
                    var script = document.createElement("script");
                    script.src = "appframework/plugins/af.desktopBrowsers.js";
                    var tag = $("head").append(script);
                    $.ui.autoLaunch = true;//We set this to true for dektop applications
                }
            else
                {
                    $.ui.autoLaunch = false;//By default, it is set to true and you're app will run right away.  We set it to false to show a splashscreen
                }
        </script>
        <script type="text/javascript">
            $.ui.useOSThemes = false;
            $.ui.splitview = false;//To don't show any menu by default and let showing them or hidding them due events
            $.ui.overlayStatusbar = true;
            $.ui.resetScrollers = false;
            //$.ui.isAjaxApp=true;
            $.feat.nativeTouchScroll=false;
        </script>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript">
            var app = 
        {
            config : {
                        web_id : 1,
                        os : 'ios',
                        language : 'English',
                        version : 1,
                        admob_id : null,
                        analytics_id : '',
                        app_store : null,
                        api_link : null,
                        web_link : "",
                        //web_link : "http://192.168.2.102/world_deaf/local/",
                        upload_user_picture_path : null,
                        upload_video_path : null,
                        upload_image_path : null,
                        store :
                                {
                                      'android' : '',
                                      'ios' : ''
                                },
                        ad_units :
                          {
                              android : {
                                          banner: '',
                                          interstitial: ''
                                        },
                              ios     : {
                                          banner: '',
                                          interstitial: ''
                                        }
                          }
                     },
            is_ready : 0,
            debug_mode : 1,
            have_back : 0,
            operation : '',
            current_page : '',
            current_program : '',
            sender_id : '',
            initialize : function()
                {
                    this.config.admob_id = ( /(android)/i.test(navigator.userAgent) ) ? this.config.ad_units.android : this.config.ad_units.ios;
                    this.config.app_store = this.config.store[this.config.os];
                    this.config.api_link = this.config.web_link + "Programs/demo/demo.php";
                    this.config.upload_user_picture_path = this.config.web_link + "Programs/demo/upload_user_pic.php";
                    this.config.upload_video_path = this.config.web_link + "Programs/demo/upload_video.php";
                    this.config.upload_image_path = this.config.web_link + "Programs/demo/upload_image.php";
                    core.bind_system_events();
                }
        }
        
        var core = 
            {
            bind_system_events : function()
                {
                    document.addEventListener('pause',system_events.on_pause, false);
                    document.addEventListener('resume',system_events.on_resume, false);
                    $(document).ready(this.validate_application_version);
                },
            validate_application_version : function()
                {
                    alert('initialized');
                }
            }
            
         app.initialize();
        </script>
    </head>
    <body>
        <div id="afui">
            <div id="splashscreen" class='ui-loader heavy'>
                <div id="home_logo_div">
                    <h1>
                        <br /><br /><br /><br /><br /><img src="images/home_logo_old.png" id="home_logo_img" />
                    </h1>
                    <br>
                    <h1>World Deaf</h1>
                </div>
            </div>
            <div id="header">
                
            </div>
            <div id="content">
                <input id="temp_value_input" class="hidden" value="" />
                <textarea id="temp_data_area" class="hidden"></textarea>
                <div id="loader"><span id="loader_message_span"></span></div>
                <div id="quite_page"><span id="quite_page_message_span">Enjoy Your Quiet</span></div>
                <div class="panel" id="empty_page" data-footer="none" data-header='none' data-nav="none"></div>
            </div>
            <nav id='left_aside' class='aside'>
                <div class='title'>&nbsp;</div>
                <ul>
                    <li>
                        <a id="aside_1_link" href="#" data-persist-ajax="true" data-refresh-ajax="false" class="icon camera mini"></a>
                        <a href="#" onclick="window.open('', '_system');" class="acenter">
                            <img src="images/home_logo.png" id="aside_logo_img" />
                        </a>
                    </li>
                </ul>
            </nav>
            <div id="navbar">
                <div id="bottom_navbar_div">
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_wall"></div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_vibrate"></div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_notifications">
                        <div class="hidden" id="notifications_count"></div>
                    </div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_settings"></div>
                </div>
                <a data-href="wall.html" data-page-id="wall_page" class="nav_item wall" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="#" id="quite_page_tab_link" class="nav_item vibrate" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="notifications.html" data-page-id="notifications_page" class="nav_item notifications" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="settings.html" data-page-id="settings_page" class="nav_item settings" data-persist-ajax="true" data-refresh-ajax="false"></a>
            </div>
            <div class="app_header" id="warning_header">
                <img src="images/loading-black.gif" id="warning_header_img" />
                <span id="warning_header_span"></span>
            </div>
        </div>
    </body>
</html>
</code>

**Comment by mouhammad-zd** [comment]
I think this will make the status more clear

````javascript
<!DOCTYPE html>
<html>
    <head>
        <title>World Deaf</title>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <!-- WARNING: for iOS 7, remove the width=device-width and height=device-height attributes. See https://issues.apache.org/jira/browse/CB-4323 -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <link rel="stylesheet" type="text/css" href="appframework/build/css/icons.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/forms.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/buttons.css" />
        <link rel="stylesheet" type="text/css" href="appframework/css/afui.css" />
        <link rel="stylesheet" type="text/css" href="appframework/plugins/css/af.popup.css" />
        <link rel="stylesheet" type="text/css" href="styles/style-ltr.css?v=2" />
        <script type="text/javascript" charset="utf-8" src="appframework/build/ui/appframework.ui.min.js"></script>
        <link rel="stylesheet" type="text/css" href="appframework/plugins/css/af.selectBox.css" />
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.selectBox.js"></script>
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.passwordBox.js"></script>
        <script type="text/javascript" charset="utf-8" src="appframework/plugins/af.popup.js"></script>
        <script>
            if (!((window.DocumentTouch && document instanceof DocumentTouch) || 'ontouchstart' in window))
                {
                    var script = document.createElement("script");
                    script.src = "appframework/plugins/af.desktopBrowsers.js";
                    var tag = $("head").append(script);
                    $.ui.autoLaunch = true;//We set this to true for dektop applications
                }
            else
                {
                    $.ui.autoLaunch = true;//By default, it is set to true and you're app will run right away.  We set it to false to show a splashscreen
                }
        </script>
        <script type="text/javascript">
            $.ui.useOSThemes = false;
            $.ui.splitview = false;//To don't show any menu by default and let showing them or hidding them due events
            $.ui.overlayStatusbar = true;
            $.ui.resetScrollers = false;
            //$.ui.isAjaxApp=true;
            $.feat.nativeTouchScroll=false;
        </script>
        <script type="text/javascript">
            var app = 
        {
            config : {
                        web_id : 1,
                        os : 'android',
                        language : 'English',
                        version : 1,
                        admob_id : null,
                        analytics_id : '',
                        app_store : null,
                        api_link : null,
                        web_link : "",
                        //web_link : "http://192.168.2.102/world_deaf/local/",
                        upload_user_picture_path : null,
                        upload_video_path : null,
                        upload_image_path : null,
                        store :
                                {
                                      'android' : '',
                                      'ios' : ''
                                },
                        ad_units :
                          {
                              android : {
                                          banner: '',
                                          interstitial: ''
                                        },
                              ios     : {
                                          banner: '',
                                          interstitial: ''
                                        }
                          }
                     },
            is_ready : 0,
            debug_mode : 1,
            have_back : 0,
            operation : '',
            current_page : '',
            current_program : '',
            sender_id : '',
            initialize : function()
                {
                    core.bind_system_events();
                }
        }
        
        var core = 
            {
            bind_system_events : function()
                {
                    alert('before initializing');
                    $(document).ready(this.validate_application_version);
                    alert('after initializing');
                },
            validate_application_version : function()
                {
                    alert('initialized');
                }
            }
            
         app.initialize();
        </script>
    </head>
    <body>
        <div id="afui">
            <div id="splashscreen" class='ui-loader heavy'>
                <div id="home_logo_div">
                    <h1>
                        <br /><br /><br /><br /><br /><img src="images/home_logo_old.png" id="home_logo_img" />
                    </h1>
                    <br>
                    <h1>World Deaf</h1>
                </div>
            </div>
            <div id="header">
                
            </div>
            <div id="content">
                <input id="temp_value_input" class="hidden" value="" />
                <textarea id="temp_data_area" class="hidden"></textarea>
                <div id="loader"><span id="loader_message_span"></span></div>
                <div id="quite_page"><span id="quite_page_message_span">Enjoy Your Quiet</span></div>
                <div class="panel" id="empty_page" data-footer="none" data-header='none' data-nav="none"></div>
            </div>
            <nav id='left_aside' class='aside'>
                <div class='title'>&nbsp;</div>
                <ul>
                    <li>
                        <a id="aside_1_link" href="#" data-persist-ajax="true" data-refresh-ajax="false" class="icon camera mini"></a>
                        <a href="#" onclick="window.open('', '_system');" class="acenter">
                            <img src="images/home_logo.png" id="aside_logo_img" />
                        </a>
                    </li>
                </ul>
            </nav>
            <div id="navbar">
                <div id="bottom_navbar_div">
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_wall"></div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_vibrate"></div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_notifications">
                        <div class="hidden" id="notifications_count"></div>
                    </div>
                    <div class="nav_b f_w_p_left bottom_navbar" id="nav_settings"></div>
                </div>
                <a data-href="wall.html" data-page-id="wall_page" class="nav_item wall" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="#" id="quite_page_tab_link" class="nav_item vibrate" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="notifications.html" data-page-id="notifications_page" class="nav_item notifications" data-persist-ajax="true" data-refresh-ajax="false"></a>
                <a data-href="settings.html" data-page-id="settings_page" class="nav_item settings" data-persist-ajax="true" data-refresh-ajax="false"></a>
            </div>
            <div class="app_header" id="warning_header">
                <img src="images/loading-black.gif" id="warning_header_img" />
                <span id="warning_header_span"></span>
            </div>
        </div>
    </body>
</html>
````

Using above code will just alert before initializing and will not do anything else so document ready break code

**Comment by imaffett** [comment]
Can you host this fully somewhere so I can see which version of the code you are using?  Also, you if you are using appframework/build/ui/appframework.ui.min.js you do not need any other JS files

**Comment by mouhammad-zd** [comment]
after hosting same example into my online web it seem this work so what is the prob and it may be an cross domain request problem and how it may be corrected ?

**Comment by mouhammad-zd** [comment]
Look this example is hosted here : http://deafworlapp.com/demo/

But it work as expected when same code is not working on ios emulator

**Comment by mouhammad-zd** [comment]
Hope this can give some more infos to reproduce the issue

I noticed this line in the console log

void SendDelegateMessage(NSInvocation *): delegate (webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

Hope that can help to track problem

Thank you in advance again !

**Comment by imaffett** [comment]
Looks like there is an error.  Are you using Cordova or something else?

**Comment by mouhammad-zd** [comment]
Yes exactly i am using cordova but the matter is even i remove the reference to the cordova.js the problem stays. And if i change the appframework to an earlier version also it works . So the problem as i can explain it is in the new update of the framework , on ios devices !

**Comment by mouhammad-zd** [comment]
Did you have any news ! I want to tell you again about the link to the online test because the link i have told about previously was broken http://deafworldapp.com/demo/

Hope you can find the issue ASAP ! Thank you in advance for your best regards !

**Comment by imaffett** [comment]
@mouhammad-zd I just tested the kitchen sink in a cordova app and $(document).ready() works fine.

**Comment by mouhammad-zd** [comment]
@imaffett Thank you for replying ! But did you test it on ios or android or both ? and which platform version ?

**Comment by VladManolache** [comment]
What version of app framework are you using ? 

I've just upgraded to app framework v2.2 from v2.1, and now device ready is not fired on iPod running iOS6. Works just fine on iOS8.

**Comment by mouhammad-zd** [comment]
The version i am use it was located in the master branch and as i can see in the top of file this signature

/*! intel-appframework - v2.1.0 - 2014-12-17 */
But when i make a comparison between all js files in my version and the official v2.2 i found the difference only in this line 

this.scrollToTop("modal_container");

So as i can say yes i am using v2.2 .........

**Comment by VladManolache** [comment]
Please try switching to v2.1.0 release.

I believe that something got broken in v2.2.0 release. Can someone else confirm ?

**Comment by imaffett** [comment]
I don't have time to hunt down bugs on iOS 6.  If you guys find what the issue is, feel free to submit a PR request fixing it.

**Comment by Rockfogel** [comment]
I can confirm this. The combination of Xcode 6.2, AF 2.2 and iOS7 will not fire $(document).ready, both in simulator and on target. Change to iOS8, and it is OK. Change to AF 2.0 and it is OK. Have not tried AF 2.1 since I have not found the official download yet (AF 2.0 was bounded with Xdk 1632).

**Comment by imaffett** [comment]
@Rockfogel.  Are you using an app from App Designer/XDK or App Framework?  Are you using the jQuery shim?  Please post a sample online so I can debug it.

**Comment by imaffett** [comment]
Fixed here https://github.com/01org/appframework/commit/409d8469f3633c3d5388bd92d354b42f6e373836

**Comment by Rockfogel** [comment]
I can confirm the the update made in AF 2.2 in 2015-04-21 in file appframework.ui.min.js did the trick.
Now it is working with the new AF2.2 and iOS7. @imaffett: Thanks for quick response. @mouhammad-zd: Hope this also solves your original problem. Good thing you posted it.
