### ISSUE TITLE
App Framework and RequireJS: How to use data-load

### ISSUE THREAD

**Issue by gch35pty** [01org/appframework#814]
Hello,
I try to use the data-load attribute. My project uses RequireJS to manage the JS files. The function to be called by the data-load Attribuite is located in the main.js which is directly loaded by RequireJS.
However the call to the function is not performed when my app runs.
But if I define the function in a script tag in the index.html then it works.
It seems that the tag "data-load" defined in index.html can not get the module func defined with RequireJS.
Does anyone have any idea why this might be?

//my func with RequreJS is as below
// myModule.js
　　define(function (){
　　　　var showCount = function (){
　　　　　　//....
　　　　};
　　　　return {
　　　　　　showCount: showCount
　　　　};
});

//the panel defined in the index.html is as below
<div class="panel" id="login" data-load="myModule.showCount" data-counter='5'> </div>

**Comment by vijayrajasekaran** [comment]
This is how i do,

index.html
-------------
<div class="upage vertical-col panel" id="panel" data-header="af-header-1" data-load="hello">
</div>

jscript.js
---------

foo () {
alert("Hello!");
}
