### ISSUE TITLE
Unable to use native scroller on windows phone (using   $.feat.nativeTouchScroll=true; )

### ISSUE THREAD

**Issue by seematalanki** [01org/appframework#815]
We have hybrid app running on both android and window phone, on which we want to use native scroll er . Following piece of code works on android but the same is failing on windows phone.
  $.feat.nativeTouchScroll=true; 
Let us know if any thing specific to windows phone has to be done

**Comment by imaffett** [comment]
No, per the documentation native scrolling is not supported on windows phone

**Comment by linoleum89** [comment]
Actually is posible, if you put this CSS:

*{
-ms-touch-action:auto;
-ms-overflow-style:auto;
}
