### ISSUE TITLE
How to enable scrolling

### ISSUE THREAD

**Issue by RonCan** [01org/appframework#816]
Hey, I want to enable scrolling for the chrome app, I try to set the style attribute to overflow:scroll;display:block the screen goes blank.

**Comment by imaffett** [comment]
Hi @RonCan  -You need to produce a demo that we can test to debug.  Also provide the device/OS you are testing against.

**Comment by RonCan** [comment]
Solved it. When I use the the $('selector').attr method, the content goes away but when I use $('selector').style.overflow=auto/visible it works. I built a chrome app from the page.

**Comment by imaffett** [comment]
Use the .css() method to set css attributes
