### ISSUE TITLE
Where can I found 2.1.0's API???

### ISSUE THREAD

**Issue by leokt** [01org/appframework#817]
Hi! We're developing mobile OA system with appframework 2.1.0's release for months,but today we suprisingly found that all online API had been replaced by latest version.Now we can only find 2.1.0's source code and examples,but that is not enough.So could you tell me where can I found 2.1.0's API???I'm looking forward for your reply.Thx.

**Comment by imaffett** [comment]
We are in the process of updating the website today.  Thanks

**Comment by imaffett** [comment]
http://app-framework-software.intel.com/af22/ will give you the 2.1/2.2 docs (2.2 is 2.1 just tagged in a different branch for maintenance reasons)
