### ISSUE TITLE
appframework 3.0 beta envent and scroll question

### ISSUE THREAD

**Issue by igeek-YZ** [01org/appframework#818]
I try to use appframework 3.0 beta in my project .but I find some questions about panel key event and put up scroll to use ajax to request data. is not good to use and I need use lots of time to study . i 'm coder for android app. i want At the top speed to make html nested in my app.Rather than how to study and study.and Can you give some example of key points?

**Comment by imaffett** [comment]
Questions like this should be asked at https://forums.html5dev-software.intel.com/ or on stackoverflow
