### ISSUE TITLE
Poor documentation on App Framework 3.0 

### ISSUE THREAD

**Issue by dargoan** [01org/appframework#821]
Hi,

Global documentation is missing on this project : about App Framework 3.0 for example.

This url : http://app-framework-software.intel.com/ presents the basic idea, with short blocks of code, but should at least contain, in addition : 
- the why of the evolutions since v2.x: why use jQuery now ? and why not jQueryMobile ? or Zepto ? or other general choices...
- a clear explanation about what files to include in the code, and what role they have.
- a step by step tutorial example, with directories and files structure for each step (i have in mind the excellent AngularJs tutorial example, for example)
- the same kind of documentation for each plugin.
- and a whole block of precisions on the examples included in the Intel XDK, with information about which version it uses etc...

As is, I've been trying to use v3.0, but couldn't go any further because of mistakes on the website. So, it was a waste of time as it makes us unable to get started quickly/at all with App Framework v3.0.

**Comment by imaffett** [comment]
Quickstart guide is at http://app-framework-software.intel.com/documentation.php

API is at http://app-framework-software.intel.com/api.php

UI Components are at http://app-framework-software.intel.com/components.php

**Comment by dargoan** [comment]
Thanks for those links Ian, i knew these by the way.
But they're exactly illustrating what could be improved : take for example the UI Components page.
We arrive at v3.0 documentation section, as there's also a link to 2.2 on this page.
Allright.
But then, when i click on "Create snippet", all snipets are showing examples of AppFramework 2.1 with CDN links! So, on this simple page we have 3 versions of App Framework : 
> 2.2 link at the top of the page
> 3.0 documentation, the current and last version of AF
> and 2.1 snippets...
Well, not very clear to me, and surely, it could be clearer.

Another example : 
in XDK, somme projects' templates (i did not verify on all) are showing a minified version of appframework. So, there are no comments. And that's impossible to tell which version is used, and what files/plugins it's getting.
Again, small details, but very troublesome when you want to start. That's my point.

Are you sure you want close this issue? Because for me, these links are not even the beginning of a solution...

**Comment by lilili87222** [comment]
I never find any document about menu Button,do your app have menu button???   link in uiinsetlist  is all broken. not any theme template also .  if I my app have three type menuButton,then I need create threen header and footer, do you think that is a good design?

**Comment by imaffett** [comment]
@dargoan I think you are confusing the XDK and App Framework.  The XDK is a consumer (like any developer) of App Framework.

@lilili87222 - yes there is a menu button https://github.com/01org/appframework/blob/master/templates/drawer.html

**Comment by dargoan** [comment]
Thanks @imaffett for your answer, but i'm not confusing between those two.
I speak about appframework. In the examples, i didn't find any coherence about documentation, version code, and appframeworks. Why bother to put minified code in examples ? Today, there are plenty of tools outhere that do minification of code.
But, maybe, things have changed since my last post, I didn't check if today it's different.

**Comment by Elchie** [comment]
Button Documentation is not clearly documented. i mean, what kind of button enable to implement other than "menuButton".. try to create my own combination of icon, but it not well displayed.
