### ISSUE TITLE
setTitle and setBackButtonText dose not work

### ISSUE THREAD

**Issue by fgithuby** [01org/appframework#822]
when open othser page url, setTitle and setBackButtonText dose not work.  they cannot be custom.
such as:
a.html
---------------
<a href='b.html'>go to b</a>
--------------

b.html
---------------
<script>
    $(document).ready(function(){
        $.afui.setBackButtonText("mybacktext");
        $.afui.setTitle("Btitle");
    });
</script>
this is b page
---------------
![Uploading 捕获.PNG . . .]()
I find that the HTML and js code I write here  cannot be seen after I click update comment.
do you have an email?

**Comment by imaffett** [comment]
Can you post an example somewhere (jsbin) to demonstrate this?

**Comment by fgithuby** [comment]
http://jsbin.com/dojususuxi/1/edit?html,css,js,console,output

**Comment by imaffett** [comment]
sorry - a working demo.

**Comment by fgithuby** [comment]
here is a simple example in the appframework source code.you edit the ajax.html, add the js code in this file. then open the index.html with brower. go to the Plugins ->   ajax  
$(document).ready(function(){
        $.afui.setBackButtonText("mybacktext");
        $.afui.setTitle("mytitle");
    });

**Comment by imaffett** [comment]
this is working as intended.  You are setting the back button and title test, THEN loading a page which overrides it.   You need to bind panel-load event and change it after

**Comment by fgithuby** [comment]
thank you very much. by the way, Where are events document? I looked through the api docs and only found touch events.

**Comment by imaffett** [comment]
http://app-framework-software.intel.com/documentation.php#afui/afui_events

**Comment by fgithuby** [comment]
I do what you told me. I bind the panelload event and change it after loading a page. the title can be change but the back button text can not.
