### ISSUE TITLE
App Force Close in Gingerbread  | App Framework 2.2 - Intel XDK 1816

### ISSUE THREAD

**Issue by vijayrajasekaran** [01org/appframework#824]
I tried building APK's using many example code. It works fine for Android Version 4.0+ but it just exits after SplashScreen in Gingerbread. Please check the attached image for the error.

Built Using:
Cordova 4.1.2

Plugins:
Device - 0.2.13
Dialogs - 0.2.11
SplashScreen - 0.3.5

![error](https://cloud.githubusercontent.com/assets/7944168/6431547/cd3d2134-c058-11e4-90a4-af855feb62cc.PNG)

**Comment by imaffett** [comment]
that's not an App Framework bug.  That's from the Intel XDK
