### ISSUE TITLE
Modal, Scroll to bottom not working

### ISSUE THREAD

**Issue by Moussawi7** [01org/appframework#825]
Hi,
I still using Af 2.2, and i am facing an issue with **scrollToBottom** where it's not working on modal panels.

```
<div id="modal_conversation" data-header="conversation_header" class="panel" data-modal="true" data-footer="modal_conversation_footer">
    <div id="conversation_container">
       <br/>   <br/>   <br/>   <br/>
	      <br/>   <br/>   <br/>   <br/>   <br/>
    </div>
    <footer id="conversation_footer">
    </footer>
    <header id="conversation_header">
    </header>
</div>
```
```javascript
   $.ui.scrollToBottom('modal_conversation');
```
how to solve this issue?
Thanks.

**Comment by imaffett** [comment]
Can you post a full demo somewhere to test? 

thanks

**Comment by Moussawi7** [comment]
Hi @imaffett ,
I created a demo code that show the issue:
[Code](http://moussawi7.com/testframe/)
[Zipped](moussawi7.com/testframe.zip)
Thank you.
