### ISSUE TITLE
How I can use content editable?

### ISSUE THREAD

**Issue by linoleum89** [01org/appframework#826]
I try to use content editable on a div, but by the nature of the framework don't allow me, instead put a class named "pressed" on the div. Thanks!

**Comment by imaffett** [comment]
add data-ignore-pressed to the div and it should work

**Comment by linoleum89** [comment]
Is not working, I have my div like this: <div id="diaryContent" contenteditable="true" data-ignore-pressed></div> or like this <div id="diaryContent" contenteditable="true" data-ignore-pressed="true"></div>

And also I'm using the JavaScript scroller not native, any idea? thanks.

**Comment by TangOwen** [comment]
Try to reset your fastclick.js first.
