### ISSUE TITLE
Cant scroll

### ISSUE THREAD

**Issue by leocrawf** [01org/appframework#827]
Since I have started using the intel appframework version 3.0 I have not been able to scroll my editor datatables see http://editor.datatables.net/

I am thinking it has something to do with the recent version changes. Any clues on how this can be fixed.

**Comment by imaffett** [comment]
Can you put a demo up?  You may have some code blocking touch events.

**Comment by leocrawf** [comment]
I sent you an email with a link to the website. Thank you.

**Comment by imaffett** [comment]
This was resolved
