### ISSUE TITLE
FastClick is not instantiated in index.html

### ISSUE THREAD

**Issue by landabaso** [01org/appframework#829]
Not sure whether/where FastClick is instantiated (in index.html and also on samples dir's)

In case it's not being instantiated, maybe consider something like:

```javascript
 55     $(document).ready(function(){
 56         if ('addEventListener' in document) {
 57         document.addEventListener('DOMContentLoaded', function() {
 58             FastClick.attach(document.body);
 59             }, false);
 60         }
 61         $.afui.launch();
 62     }); 
```
From: [FastClick ReadMe in GitHub](https://github.com/ftlabs/fastclick)

**Comment by imaffett** [comment]
Can you report the following

Device it's failing on

OS it's failing on

Sample test case that's failing

**Comment by landabaso** [comment]
It's not failing. Code is OK. Apps will run smooth in most of the cases anyway since modern browsers do not need FastClick anyway when using <meta name="viewport" content="width=device-width, initial-scale=1">.

However, I don't see the point in loading a library and then never using it. Perhaps it's instantiated somewhere I could not find. Just in case I wanted to let you know that it looks like FastClick is not being instantiated in the code.

**Comment by imaffett** [comment]
It is indeed being loaded, but only when it's available.  It's up to the user to include it or not.  And iOS still has the issue, so the "most modern browsers" logic fails.

https://github.com/01org/appframework/blob/master/src/af.ui.js#L33

**Comment by landabaso** [comment]
Thanks for pointing where FastClick is loaded. I believe iOS does not have the issue for slow taps anymore (at least on iOS 8). A short explanation in the docs describing that AF automatically instantiates FC when loaded would help. Up to you guys. Thanks again!
