### ISSUE TITLE
Using data-load will not fired each time panel is loaded

### ISSUE THREAD

**Issue by mouhammad-zd** [01org/appframework#830]
Hello ! When i use the data-load attribute to load a specific function when panel is loaded . The function fired just the first time panel is loaded , but when the same panel is re-loaded the function is not fired !

 My application use the side menu concept so the user can open same page even if he is in the same page .

For more explanation :

i have look like this menu :
      -page1.html
      -page2.html
      -page3.html

If the user click on the "page1.html" the data-load function fired correctly , even if the user click on page2.html the data-load function fired correctly .

But if the user is in the page2.html and he clicks the page2.html link the function is not fired

So what is the matter and how to solve this issue ?

**Comment by mouhammad-zd** [comment]
3 days and no one answer my question ! Please anyone have the solution for my case !

Note i am using the framework 2.2 !

**Comment by imaffett** [comment]
Hi @mouhammad-zd 

So you are on page2.html and clicking a link for page2.html correct?  This will NOT load any events since you are trying to load the current page.

**Comment by mouhammad-zd** [comment]
But i want to be able to do a refresh when i click the link to the page i am inside how can i achieve that ?

**Comment by imaffett** [comment]
https://github.com/01org/appframework/blob/2.2/ui/appframework.ui.js#L1737 - that is where it kicks out.  You could add logic there to trigger the events you would like

**Comment by mouhammad-zd** [comment]
Thank you !

My comment will have 2 parts on directed to people need my workout and second to the developer
Hope my commend may help someone :)
<pre>
/* To people who may need this workout :*/
</pre>

In my case as i can assume that the <pre>updatePanel</pre> function have not parsing again the function who have the same name as the <pre>data-load</pre> attribute .

So first i added this simple function to call a function by name
<pre>
function call_function(fn_name,data)
    {
        fn_name(data);
    }
</pre>

then i am going to add the following instruction into the end of the function <pre>updatePanel</pre> in the file <pre>appframework.ui.js</pre>

<pre>
var reload_function = $(b).attr('data-reload');
if(typeof reload_function !== 'undefined' && reload_function !== null)
     {
          call_function(reload_functions[reload_function],{});
     }
</pre>

Then i add an object to handle my reload functions
<pre>
var reload_functions = 
    {
         "page_name" : function()
               {
                 ....... //Code goeas here
               }
    }
</pre>

And finishing by adding <pre>data-reload="[function_name]"</pre> attribute to each panel i want to be reloaded , where [function_name] is the name of the function inside the reload_functions object that will act as reloader of current panel

/-------------------------------------------------------------------------------------------------------------------------/

Conclusion:
Assume i have panel

```html
<div class="panel" id="contactus_page" data-load="open_contact_us_page" data-reload="contact_us">
........//Content goes here
</div>
```

So when i load the contactus_page panel for the first time the function who have the same name as the <pre>data-load</pre> attribute is parsed
And when i click from the menu again to enter the contactus_page the function who have the same name as the <pre>data-reload</pre>  attribute is parsed

Hope that someone  may find this usefull :)

<pre>
/* For the developer */
</pre>

i think you can do it by default in the <pre>updatePanel</pre> function by testing the data-reload attribute and if attribute is found and equal "true" call the function have name as the <pre>data-load</pre>attribute

**Comment by mouhammad-zd** [comment]
Thank you !

My comment will have 2 parts one directed to people need my workout and second to the developer
Hope my comment may help someone :)
<pre>
/* To people who may need this workout that what i do :) :*/
</pre>

In my case as i can assume that the <pre>loadDiv</pre> function and as @imaffett mentioned above , have not parsing the function who have the same name as the <pre>data-load</pre> attribute when i am inside the same page.

So first i added this simple function to my scripts to call a function by name
<pre>
function call_function(fn_name,data)
    {
        fn_name(data);
    }
</pre>

then i am going to add the following code

<pre>
var reload_function = $(g).attr('data-reload');
if(typeof reload_function !== 'undefined' && reload_function !== null)
	{
		call_function(reload_functions[reload_function],{});
	}
</pre>

after the below instruction

<pre>
    if(g===this.activeDiv&&!c)
</pre>

in the function <pre>loadDiv</pre> in the file <pre>appframework/build/ui/appframework.ui.min.js</pre>

**** Note the variables named g and c in my minified version it may named something else in yours ****

/////////////////////////////////////////////////////////////////////////////////
As i can told you that this may be found in the uncompiled files too, in the same place @imaffett give me link to .
But because i am using the minified version so i have take the hard decision to understand the minified code :)

well if you are using the uncompiled version and you will compile it personnaly i can told you that this code will be found at the line 1737 in the file appframework.ui.js under the path appframework\ui\ and you could convert it to become

<pre>
if (oldDiv === currWhat)//Code from plugin
	{
		var reload_function = $(oldDiv).attr('data-reload');//new instruction
		if(typeof reload_function !== 'undefined' && reload_function !== null)//new instruction
			call_function(reload_functions[reload_function],{});
	    return;
	}
</pre>
///////////////////////////////////////////////////////////////////////////////
Then i add an object to handle my reload functions
<pre>
var reload_functions = 
    {
         "page_name" : function()
               {
                 ....... //Code goes here or actually may  be just the call to the data-load function
                 open_contact_us_page();
               }
    }
</pre>

And finishing by adding <pre>data-reload="[function_name]"</pre> attribute to each panel i want to be reloaded , where [function_name] is the name of the function inside the reload_functions object that will act as reloader of current panel

/-------------------------------------------------------------------------------------------------------------------------/

Conclusion:
Assume i have panel

```html
<div class="panel" id="contactus_page" data-load="open_contact_us_page" data-reload="contact_us">
........//Content goes here
</div>
```

So when i load the contactus_page panel for the first time the function who have the same name as the <pre>data-load</pre> attribute is parsed
And when i click from the menu again to enter the contactus_page the function who have the same name as the <pre>data-reload</pre>  attribute is parsed

Hope that someone  may find this usefull :)

<pre>
/* For the developer */
</pre>

i think you can do it by default in the <pre>loadDiv</pre> function by testing the data-reload attribute of the panel and if attribute is found and equal "true" call the function have name as the <pre>data-load</pre>attribute

Hope this can be done because i think it is mandatory to reparse script on loadingDiv when user need this because some applications logic need that each time the page is accessed some functions to be called . So hope this can be done and be a new feature of this lovely framework :)

Thank you in advance for any regards !

**Comment by imaffett** [comment]
@mouhammad-zd - You can always fork the repo and make the change, then submit a pull request.
