### ISSUE TITLE
Panel load/unload or transition events not firing.

### ISSUE THREAD

**Issue by brickyenne** [01org/appframework#831]
Events like "panelload" are not firing. Attached to particular panel or to the document or window to fire on any panel and no, no event is fired.

**Comment by muchengit** [comment]
you can use it like : 
$("#afuidemo").on('panelload', function() {
        alert("hi");
});

**Comment by imaffett** [comment]
Which version of AF are you testing?  Also which device/OS.  Can you please post a full example?

**Comment by brickyenne** [comment]
I’m using AF 3.0. Well, it’s simple I just binded the event to the panel just as the docs suggests:


$("#main").bind('panelload', function() {
alert("hi");
});


…but nothing happens. Tested directly on the XDK which isn’t supposed to have the events issues Androids are known to have. I think I’m going back to AF 2.1 or 2.2 as upon further testing found 3.0 still has some issues on Android. Tested 2.1 up to 4.4.4 with no problems.


Thank you!


Alfredo.






Enviado desde Correo de Windows





De: Ian Maffett
Enviado el: ‎lunes‎, ‎16‎ de ‎marzo‎ de ‎2015 ‎05‎:‎43‎ ‎a. m.
Para: 01org/appframework
CC: brickyenne





Which version of AF are you testing? Also which device/OS. Can you please post a full example?

**Comment by seekchange** [comment]
Did you make sure to set the bind only after afui is launched and after checking $.afui.ready?
