### ISSUE TITLE
how to make the slideright to goback look like native app effect？

### ISSUE THREAD

**Issue by wierli** [01org/appframework#832]
I used bind a function with slide right to run the $goback , but the effect not seems like the native app.

**Comment by imaffett** [comment]
Sorry, I do not understand.  Can you provide a demo?

**Comment by wierli** [comment]
Tomorrow , I will sent a link form the demo . And so sorry made you in trouble.

**Comment by wierli** [comment]
I have another question that can not select  text to copy it in all pannel

**Comment by imaffett** [comment]
we disable text selection

https://github.com/01org/appframework/blob/master/build/af.ui.base.css#L4

**Comment by wierli** [comment]
$('#panel_A').bind("swipeRight", function() {
                $.ui.loadContent("#main", false, true, "slideright");
              });


I use this function to achieved Swipe Back,but it not Look like a native application

**Comment by imaffett** [comment]
You'll have to find a plugin for that.  We had one in App Framework 2.2, but did not port that over.
