### ISSUE TITLE
afui3.0     $.afui.setBackButtonText  is not working

### ISSUE THREAD

**Issue by muchengit** [01org/appframework#833]
1.Test cases : $.afui.setBackButtonText("about");
2.error : the BackButtonText not change
3.testing on all Device

**Comment by muchengit** [comment]
@imaffett why?

**Comment by imaffett** [comment]
@muchengit "why" what?

**Comment by muchengit** [comment]
How to use $.afui.setBackButtonText("about");？Can you give me a demo? 
my email  392567445@qq.com

**Comment by isaachs** [comment]
need to fix two functions:
![1](https://cloud.githubusercontent.com/assets/893261/6803152/aba0a562-d270-11e4-9cee-8ee5a47bfb97.jpg)
![2](https://cloud.githubusercontent.com/assets/893261/6803153/ace8e182-d270-11e4-81a8-e11c63e221e6.jpg)

**Comment by imaffett** [comment]
@isaachs  - can you provide some context here?  I'm not sure what you are saying

**Comment by isaachs** [comment]
appframework.ui.js

**Comment by isaachs** [comment]
@imaffett appframework.ui.js

**Comment by imaffett** [comment]
That provides no information.  Can you explain what is broken about those functions?  Please view the readme.md for reporting bugs

```
Please use github issues and file any bugs with the following

Any error messages from the console

Line numbers of offending code

Test cases

Description of the error

Expected result

Browser/Device you are testing on
```
