### ISSUE TITLE
Anchor Properties  data-persist-ajax="true" and data-refresh-ajax="true" not working!

### ISSUE THREAD

**Issue by cmwong** [01org/appframework#847]
Hi,

I download App Framework from http://app-framework-software.intel.com

Referring this Anchor Properties document http://app-framework-software.intel.com/documentation.php#afui/afui_anchors

These 2 data- prop is not working.
I check from the source code, I cannot found these 2 prop.

From source only having 
    var forceRefresh=anchor.getAttribute("data-refresh");  //line 1165 in function loadAjax()

Question:
Do I download the wrong version? Or I'm referring to wrong documentation?

**Comment by cmwong** [comment]
I play with data-refresh="true"
the following is my fixed for function loadAjax()

        loadAjax: function(target, newTab, back, transition, anchor) {
            var that=this;
            var crc=crc32(target);
            var found=$(".panel[data-crc='"+crc+"']");
            var forceRefresh=anchor.getAttribute("data-refresh");

            if(found.length>0){
                if(forceRefresh){
                    that.showLoading&&that.showMask("Loading Content");
                    $.ajax(target).then(function(res){
						if(!$(res).hasClass('panel')) {
							// cmwong 20150404
							// do not hv panel, just replace everything
							// use append so that the js in panel will execute
							found.empty().append(res);
						} else {
							// cmwong 20150404
							// only the first panel
							// only take childnodes under panel (do not want the panel node)
							var $res=$.create("div",{html:res});
							found.empty().append( $( $res.find(".panel")[0] ).html() );
						}
                        that.showLoading&&that.hideMask();
                        that.loadContent("#"+found.prop("id"),newTab,back,transition,anchor);
                    });
					// cmwong 20150404
					// return move here, if not it with fire 2 times ajax
					return;
                } else {
                    that.loadContent("#"+found.prop("id"),newTab,back,transition,anchor);
					return;
				}
            }
            that.showLoading&&that.showMask("Loading Content");
            $.ajax(target).then(function(res){
                var $res=$.create("div",{html:res});
				//cmwong 20150404
				//the first node hasClass panel
				if(!$(res).hasClass('panel')) {
                    $res=$res.attr("data-title",(target));
                    $res.prop("id",crc);
                    $res.addClass("panel");
                } else {
					// only take the first found panel
                    $res=$( $res.find(".panel")[0] );
					if(!$res.prop('id')) {
						$res.prop("id",crc);
					} 
                }
                $(that.activeDiv).closest(".pages").append($res);
                $res.attr("data-crc",crc);
                that.showLoading&&that.hideMask();
                that.loadContent("#"+$res.prop("id"),newTab,back,transition,anchor);
            }).fail(function(res){
                that.showLoading&&that.hideMask();
                console.log("Error with ajax request",res);
            });
        },

**Comment by imaffett** [comment]
Hi @cmwong - I'm closing this issue.  Please submit a pull request to fix it.
