### ISSUE TITLE
afui.setBackButtonVisbility invalid in AppFramework API

### ISSUE THREAD

**Issue by 1098880928aa** [01org/appframework#851]
http://app-framework-software.intel.com/api.php#$_afui_setBackButtonVisbility

$.afui.setBackButtonVisbility(true)    is invalid
it should be setBackButtonVisibility.
The spelling mistakes in the official website of the function

**Comment by imaffett** [comment]
http://app-framework-software.intel.com/api.php#$_afui_setBackButtonVisbility

That's been the link.  I think you have an old link?  clicking the one you have just loads the API page

**Comment by 1098880928aa** [comment]
your link is same of my link, this $.afui.setBackButtonVisbility(true) is error of document,it's right way of $.afui.setBackButtonVisibility(true);

**Comment by csroad** [comment]
$.afui.setBackButtonVisbility(true) is invalid
it should be setBackButtonVisibility.

i have this problem too.please modify documents.
