### ISSUE TITLE
$.afui.setTitle don't work at two view panel

### ISSUE THREAD

**Issue by hggq** [01org/appframework#858]
&lt;div class=&quot;view&quot; id=&quot;mainview&quot;&gt;<br />
&lt;header&gt;<br />
&lt;h1&gt;Tab View&lt;/h1&gt;<br />
&lt;/header&gt;<br />
&lt;div class=&quot;panel&quot; data-title=&quot;Profile&quot; id=&quot;test&quot;&gt;<br />
&lt;a href=&quot;#showv&quot;  data-transition=&quot;up-reveal&quot;&gt;Go to Other view&lt;/a&gt;<br />
&lt;/div&gt;<br />
&lt;/div&gt;<br />
&lt;div class=&quot;view&quot; id=&quot;otherview&quot;&gt;<br />
&lt;header&gt;&lt;h1&gt;&lt;/h1&gt;&lt;/header&gt;<br />
&lt;div class=&quot;pages&quot;&gt;<br />
&lt;div class=&quot;panel&quot; id=&quot;showv&quot;&gt;<br />
This is otherview<br />
&lt;/div&gt;<br />
&lt;/div&gt;<br />
&lt;/div&gt;

$("#showv").bind("panelload",function(){
	               $.afui.goBack();
			$.afui.setTitle("newtitle");
			console.log($.afui.activeDiv.id);
	    });

output:    test 

otherview header title is empty 
mainview header title firebug shows newtitle

**Comment by imaffett** [comment]
You are setting the title before the transition ends.
