### ISSUE TITLE
how to custom header

### ISSUE THREAD

**Issue by xujianrj** [01org/appframework#861]
I have 4 different panels having the same footer and different header ,
the different header having different button there.
in AF2 I am enable to using the data-header='headerid' to custom header for each panel,
now i have upgrade to AF3 ,I can not find there is any option work ,
in AF3 ,as they have same footer ,I have to place them in same view.
please tell me what is the usage ?

**Comment by wierli** [comment]
you can make a same content , just data-header is diferent , and load this content

**Comment by xujianrj** [comment]
the data-header attr on panel do not work on AF3

**Comment by imaffett** [comment]
@xujianrj - you can write a wrapper using the panel load event to do this.  I had it in another issue ticket on here.

AF3 is focused on compisition - so views should have the same header/footer.
