### ISSUE TITLE
Swipe to reveal breaking list scroll

### ISSUE THREAD

**Issue by langowskiadam** [01org/appframework#869]
I try to use "Swipe to reveal", but I notice that on swipe elements I'm not able to scroll list, even in compile sources from this repo. 
I think it's bug, couse Swipe to reveal" is designed for list view.

I'm looking forward bugfix or any help.

Kind regards

**Comment by imaffett** [comment]
@langowskiadam please post a demo

**Comment by langowskiadam** [comment]
This "App Framework Kitchen Sink" in Touch Event menu can be a demo. 
I check it and is not working as well

**Comment by imaffett** [comment]
Please provide your device, OS version and browser

**Comment by langowskiadam** [comment]
I'm not using browser. I build for android via IntelXDK. Device: LG L90, Android 4.4.2

**Comment by langowskiadam** [comment]
Finally I figured it out. It was because swipe elements need scroll class to enabling scrolling. There is nothing about it in documentation so I update example here: https://github.com/01org/appframework/pull/879

**Comment by imaffett** [comment]
Thanks - I will merge your fix
