### ISSUE TITLE
Android Phonegap Scroll is not working at all

### ISSUE THREAD

**Issue by aartpieete** [01org/appframework#874]
Hi,

I am a novice, and not sure what code to put up (will be happy to produce if requested what), using app framework/phone gap. All works fine on iOS but on Android nothing will scroll, page scroll down, picture slide etc.. I realize this is a very unspecific question, but any support/help would be very welcome. tx!

**Comment by imaffett** [comment]
@aartpieete can you give us a demo, along with which phone device and OS you are testing against?

**Comment by aartpieete** [comment]
Hi @imaffett 

Tx for your quick reply! The phone is a custom build from a retail store in holland (model number H3), running on 4.4.2. With a demo you mean I send you the android code? I can do that, via dropbox?

**Comment by imaffett** [comment]
@aartpieete - yep send it to ian.maffett@intel.com

**Comment by aartpieete** [comment]
Hi Ian, did you have a chance to look at my mail?

**Comment by leocrawf** [comment]
Any word on this. I am having similar issues where no scrolling whatsoever happens.

**Comment by imaffett** [comment]
@leocrawf - He was using AF 2.0.  I helped him upgrade to 2.2 and it is working.  You need to provide a demo for someone to look at it.
