### ISSUE TITLE
How to use zepto

### ISSUE THREAD

**Issue by mcdnf** [01org/appframework#885]
How to use zepto

**Comment by imaffett** [comment]
@mcdnf  for App Framework 3 ?  Just include it instead of jQuery.  For 2.2, it's not supported

**Comment by mcdnf** [comment]
When my project have 10000+ pages, App Framework 3  can  working?

**Comment by JoeSchr** [comment]
Sadly it's not so simple. Actually it fails in the first lines (line 12) of following code:
```
/**
 * af.shim.js
 * @copyright Intel 2014
 * @author Ian Maffett
 * @description jQuery helper functions for App Framework
 */
/* jshint eqeqeq:false */
(function($,window){
    "use strict";
>  jQuery.event.props.push("touches");
    jQuery.event.props.push("originalTouches");
    jQuery.event.props.push("changedTouches");
```

Is there anything I can do about it?

**Comment by SpectatorSports** [comment]
Hey @JoeSchr  - thanks for pointing this out.  It should be easy to fix.  I'll try to look into it today.
