### ISSUE TITLE
How to disappeaer the header&footer in some panels

### ISSUE THREAD

**Issue by lianghuiyuan** [01org/appframework#887]
For example: 
In my "Login" panel, it don't need header&footer, but when entered in "register" panel, it need a back button and header&footer for navigation to "Login" panel, the same situation in "find my password" panel need to back to "Login" panel.
So I need to disappear header&footer in "Login" panel, but appear header&footer in other panels in the page.
I work with AF3.0, Could anyone help me to solve it?

**Comment by Moussawi7** [comment]
you can do that by passing ***none*** to data-header/data-footer.
example:
```<div id="login_container" class="panel" data-header="none" data-footer="none" data-load="init_login" data-unload="destroy_login">```
