### ISSUE TITLE
Orientation portrait landscape layout problem Android 5.1

### ISSUE THREAD

**Issue by Udinra** [01org/appframework#904]
Hi,

I am facing same problem as mentioned in https://github.com/01org/appframework/issues/700 . The Android version is 5.1 (Huawei Honor 6 plus). The app is created using latest version of Intel XDK.

Do let me know if more information is required from my side.

**Comment by imaffett** [comment]
which version of app framework are you using?

**Comment by Udinra** [comment]
Thanks for response. I am using version 2.1 (the one which App Designer creates by default

**Comment by imaffett** [comment]
That's most likely the issue.  AF 2.1 isn't support.  AF 2.2 and 3.0 are currently supported.

**Comment by Udinra** [comment]
I will try to port the app to version 2.2. But this is something Intel should also work on. Version 2.1 is the  one created by App Designer and there is no option for version 2.2 or 3.0.

**Comment by imaffett** [comment]
@Udinra  - AF 3.0 is supported in App Designer.

**Comment by Udinra** [comment]
@imaffett Sorry but it is not at least in current version of Intel XDK. For example if you choose the template Tab View App (with App Designer) the App Framework files included point to version 2.1. But the UI framework will be displayed as App Framework 3.

I read somewhere (do not have link though) on Intel XDK site that App Framework 3 integration in App Designer is planned by 2015 year end.

**Comment by imaffett** [comment]
Hi @Udinra 

The template project is a sample.  If you start with a blank project and use App Designer, you can pick 2.1 or 3.0.

FYI - I work at Intel on the XDK team.  I'm sure it's released.
